### ISSUE TITLE
Bad replace in `joinURL` function

### ISSUE THREAD

**Issue by jaromanda** [lchrennew/es-fetch-api#1]
Currently you do `path.replace(/^\//, '').replace('/\/$/', '')`

the second replace has a string as the first argument that should be a regexp

i.e. it should be `path.replace(/^\//, '').replace(/\/$/, '')`

or just `path.replace(/^\/|\/$/g, '')` for both in one replace

By the way, glad I stumbled on this library, was working on something very similar, but this is far more elegant. Thank you

**Comment by lchrennew** [comment]
> Currently you do `path.replace(/^\//, '').replace('/\/$/', '')`
> 
> the second replace has a string as the first argument that should be a regexp
> 
> i.e. it should be `path.replace(/^\//, '').replace(/\/$/, '')`
> 
> or just `path.replace(/^\/|\/$/g, '')` for both in one replace
> 
> By the way, glad I stumbled on this library, was working on something very similar, but this is far more elegant. Thank you

Fixed.
Thank you very much! Would you like to join this project?

**Comment by jaromanda** [comment]
> Thank you very much! Would you like to join this project?

Let me think about that. 

Just want to say though, I replaced axios in a vue project using this library by creating a "shim", so I just import this library through my shim and haven't had to change the rest of the code yet. Everything works great, and I don't need to rush to change the axios calls to this all at once.

Before you ask, the "shim" is quite specific to my app, it's not like it could be used in a generic way.
